### ISSUE TITLE
Templates not working

### ISSUE THREAD

**Issue by backpack5689** [sawhney17/logseq-pdf-export#43]
Hey all,

I believe this is related to another, already closed issue, as I am seeing the same error being thrown. Didn't want to resurrect the old one though.

I'm receiving the following error when attempting to export a page. Appears to be in `index.aa958999.js:151`

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at zl (index.aa958999.js:151:2642)
     at Ac (index.aa958999.js:153:889)
```
Let me know if there's a work around for this!

**Comment by michaelaye** [comment]
Same here, same errors, using Logseq 0.9.10
