### ISSUE TITLE
Error: ... is not a valid UUID string for [text](((UUID)))

### ISSUE THREAD

**Issue by Red-Skuller** [sawhney17/logseq-pdf-export#49]
I can only print with retained formatting. If i try templates it throws this error:

Uncaught (in promise) Error: (65899250-e022-4b46-96e9-b8e030e2dabe is not a valid UUID string.
    at $logseq$sdk$utils$uuid_or_throw_error$$ (main.js:94653:9)
    at br.$logseq$api$block$get_block$$ (main.js:94716:427)
    at br.R (lsplugin.core.js:2:49447)
    at br.<anonymous> (lsplugin.core.js:2:93271)
    at a.emit (lsplugin.core.js:2:28521)
    at X.<anonymous> (lsplugin.core.js:2:88623)
    at lsplugin.core.js:2:53506
    at Array.forEach (<anonymous>)
    at X.listener (lsplugin.core.js:2:53491)
   
   It seems it doesn't support this style of links [text](((UUID)))
![Screenshot_20231230_130939](https://github.com/sawhney17/logseq-pdf-export/assets/79913098/bb012554-60b1-4ad1-9778-0a823c01d65e)
![Screenshot_20231230_131012](https://github.com/sawhney17/logseq-pdf-export/assets/79913098/76bcbf30-3f20-4bdf-9cc2-0610779c83d7)

**Comment by sdasda7777** [comment]
Same here, this bug is bizarre :/

![image](https://github.com/sawhney17/logseq-pdf-export/assets/17746796/f3f3f288-3f47-4795-a7a6-aaf6e9046b47)

**Comment by sdasda7777** [comment]
@Red-Skuller, could you clarify what the expected behaviour is?

**Comment by Red-Skuller** [comment]
It should export [text](((UUID))) as text

**Comment by sdasda7777** [comment]
With my fix, it seems to export `[text](((UUID)))` as just `text` with no link, is that okay?

![image](https://github.com/sawhney17/logseq-pdf-export/assets/17746796/3134fed7-37a4-448b-b989-702d69357c1e)

![image](https://github.com/sawhney17/logseq-pdf-export/assets/17746796/b3b1f1a5-c62d-44d9-880c-400e8c4e3698)

Strangely enough, `[text]((UUID))` exports to `[text]Header at given UUID`. I'm not completely sure how this feature was envisioned to work 🤔

**Comment by Red-Skuller** [comment]
Yes. That's plenty. Thank you!

**Comment by sdasda7777** [comment]
Great, no problem 😄 But to be honest I'm not sure how soon is one of the maintainers (@sawhney17 or @kumaresh0) likely to review it 😅
