### ISSUE TITLE
Blocked from a frame from accessing a cross-origin frame Error

### ISSUE THREAD

**Issue by rubbsdecvik** [sawhney17/logseq-pdf-export#8]
Logseq version: 0.6.5
Plugin Version: 2.0.2

When attempting to export a page via PDF, I get the following error:
![image](https://user-images.githubusercontent.com/129744/162234664-455252e0-2705-43b5-b5d9-1e0765b4955d.png)

No PDF Preview or file is generated.

I will include a redacted log output below.

```
index.987b6f28.js:50 attempts
index.987b6f28.js:50 template1
index.987b6f28.js:71 1
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 1
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 1
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 5
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 4
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 4
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:71 4
index.987b6f28.js:71 1
index.987b6f28.js:71 2
index.987b6f28.js:71 2
index.987b6f28.js:71 3
index.987b6f28.js:71 3
index.987b6f28.js:75 # 2022-04-06
<redacted>
index.987b6f28.js:75 # 2022-04-06
<redacted
index.987b6f28.js:75 <h1>2022-04-06</h1>
<redacted>
index.987b6f28.js:75 uncaught (in promise) domexception: blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at lsp://logseq.io/logseq-pdf-export-plugin/dist/assets/index.987b6f28.js:75:4282
(anonymous) @ index.987b6f28.js:75
lsp://logseq.io/logseq-property-visualizer/logo.png:1 get lsp://logseq.io/logseq-property-visualizer/logo.png net::err_file_not_found
image (async)
a @ main.js:35
jf @ main.js:160
gj @ main.js:197
hk @ main.js:197
hh @ main.js:197
mm @ main.js:190
(anonymous) @ main.js:96
w.unstable_runwithpriority @ main.js:29
tf @ main.js:95
vh @ main.js:95
uh @ main.js:95
nj @ main.js:185
enqueueforceupdate @ main.js:248
q.forceupdate @ main.js:15
(anonymous) @ main.js:86170
(anonymous) @ main.js:86089
$app.$cljs$core$reset_bang_$$ @ main.js:9009
$app.$cljs$core$swap_bang_$$.$cljs$core$ifn$_invoke$arity$variadic$ @ main.js:71667
$frontend$state$set_modal_bang_$cljs$0core$0ifn$0_invoke$0arity$02$$ @ main.js:25170
$frontend$state$set_modal_bang_$cljs$0core$0ifn$0_invoke$0arity$01$$ @ main.js:25162
$frontend$components$plugins$open_plugins_modal_bang_$$ @ main.js:59738
(anonymous) @ main.js:128153
$app.$jscompiler_prototypealias$$.$cljs$core$ifn$_invoke$arity$1$ @ main.js:79814
$switch__21956__auto__$jscomp$47$$ @ main.js:63777
$frontend$handler$events$run_bang__$_state_machine__21957__auto____1$$ @ main.js:63814
$cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ @ main.js:13994
(anonymous) @ main.js:14006
(anonymous) @ main.js:88837
$cljs$core$async$impl$dispatch$process_messages$$ @ main.js:13785
$channel$jscomp$1$$.port1.onmessage @ main.js:5035
main.js:3667 "================"

main.js:3667 "use the following to debug your datalog queries:"

main.js:3667 {:title "🔨 now",
 :query
 [:find
  (pull ?p [*])
  :in
  $
  ?start
  ?today
  :where
  [?p :block/marker ?marker]
  [(contains? #{"now" "doing"} ?marker)]],
 :inputs [:365d :today],
 :result-transform
 (fn [result] (sort-by (fn [h] (get h :block/priority "z")) result)),
 :collapsed? false, 
 :breadcrumb-show? true}

main.js:3667 "inputs (post-resolution):"

main.js:3667 [20210407 20220407]

main.js:3667 "query-opts:"

main.js:3667 {}

main.js:3667 "================"

main.js:3667 "use the following to debug your datalog queries:"

main.js:3667 {:title "🔥 overdue",
 :query
 [:find
  (pull
   ?b
   [:db/id
    :block/uuid
    :block/parent
    :block/left
    :block/collapsed?
    :block/format
    :block/refs
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/page
     [:db/id :block/name :block/original-name :block/journal-day]}
    {:block/_parent ...}])
  :in
  $
  ?start
  ?next
  :where
  [?b :block/marker ?marker]
  [?b :block/deadline ?d]
  [(contains? #{"todo" "doing" "now" "later" "waiting"} ?marker)]
  [(>= ?d ?start)]
  [(<= ?d ?next)]],
 :inputs [:365d :1d],
 :result-transform
 (fn [result] (sort-by (fn [h] (get h :block/priority "z")) result)),
 :collapsed? false, 
 :breadcrumb-show? false}

main.js:3667 "inputs (post-resolution):"

main.js:3667 [20210407 20220406]

main.js:3667 "query-opts:"

main.js:3667 {}

main.js:3667 "================"

main.js:3667 "use the following to debug your datalog queries:"

main.js:3667 {:title "📅 next",
 :query
 [:find
  (pull ?p [*])
  :in
  $
  ?start
  ?next
  :where
  [?p :block/marker ?marker]
  (or
   [?p :block/scheduled ?d]
   [?p :block/deadline ?d]
   [?p :block/journal-day ?d])
  [(contains? #{"now" "later" "todo" "waiting"} ?marker)]
  [(> ?d ?start)]
  [(< ?d ?next)]],
 :inputs [:today :7d-after],
 :result-transform
 (fn [result] (sort-by (fn [h] (get h :block/priority "z")) result)),
 :collapsed? false, 
 :breadcrumb-show? false}

main.js:3667 "inputs (post-resolution):"

main.js:3667 [20220407 20220414]

main.js:3667 "query-opts:"

main.js:3667 {}

main.js:3667 "================"

main.js:3667 "use the following to debug your datalog queries:"

main.js:3667 {:title "📚 backlog",
 :query
 [:find
  (pull ?p [*])
  :in
  $
  ?start
  ?today
  :where
  [?p :block/marker ?marker]
  [(contains? #{"later" "todo" "waiting"} ?marker)]],
 :inputs [:365d :today],
 :result-transform
 (fn [result] (sort-by (fn [h] (get h :block/priority "z")) result)),
 :collapsed? true, 
 :breadcrumb-show? false}

main.js:3667 "inputs (post-resolution):"

main.js:3667 [20210407 20220407]

main.js:3667 "query-opts:"

main.js:3667 {}

lsp://logseq.io/logseq-property-visualizer/logo.png:1 get lsp://logseq.io/logseq-property-visualizer/logo.png net::err_file_not_found
image (async)
a @ main.js:35
jf @ main.js:160
gj @ main.js:197
hk @ main.js:197
hh @ main.js:197
mm @ main.js:190
(anonymous) @ main.js:96
w.unstable_runwithpriority @ main.js:29
tf @ main.js:95
vh @ main.js:95
uh @ main.js:95
nj @ main.js:185
enqueueforceupdate @ main.js:248
q.forceupdate @ main.js:15
(anonymous) @ main.js:86170
(anonymous) @ main.js:86089
$APP.$cljs$core$reset_BANG_$$ @ main.js:9009
$APP.$cljs$core$swap_BANG_$$.$cljs$core$IFn$_invoke$arity$variadic$ @ main.js:71667
$frontend$state$set_modal_BANG_$cljs$0core$0IFn$0_invoke$0arity$02$$ @ main.js:25170
$frontend$state$set_modal_BANG_$cljs$0core$0IFn$0_invoke$0arity$01$$ @ main.js:25162
$frontend$components$plugins$open_plugins_modal_BANG_$$ @ main.js:59738
(anonymous) @ main.js:128153
$APP.$JSCompiler_prototypeAlias$$.$cljs$core$IFn$_invoke$arity$1$ @ main.js:79814
$switch__21956__auto__$jscomp$47$$ @ main.js:63777
$frontend$handler$events$run_BANG__$_state_machine__21957__auto____1$$ @ main.js:63814
$cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ @ main.js:13994
(anonymous) @ main.js:14006
(anonymous) @ main.js:88837
$cljs$core$async$impl$dispatch$process_messages$$ @ main.js:13785
$channel$jscomp$1$$.port1.onmessage @ main.js:5035
```

**Comment by sawhney17** [comment]
Looks like I have to push a change to the logseq marketplace repo.

Current altnerative is to download the release normally and load unpacked.

**Comment by sawhney17** [comment]
If you reinstall the plug-in from the marketplace it should work

**Comment by rubbsdecvik** [comment]
That worked! Thank you.

**Comment by bserrao** [comment]
Hey there,

I still get this issue... unable to export to PDF.
Logseq  Version 0.7.7
Plugin Version 2.2.4
SO Win10

`Uncaught DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at iZ (lsp://logseq.io/logseq-pdf-export-plugin/dist/assets/index.0630bad3.js:140:216)`

**Comment by sawhney17** [comment]
Try reinstall the plugin

**Comment by bserrao** [comment]
> Try reinstall the plugin
> […](#)
> On 25 Jul 2022 at 3:55 PM +0530, bserrao ***@***.***>, wrote: Hey there, I still get this issue... unable to export to PDF. Logseq Version 0.7.7 Plugin Version 2.2.4 SO Win10 Uncaught DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame. at iZ (lsp://logseq.io/logseq-pdf-export-plugin/dist/assets/index.0630bad3.js:140:216) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

That did the trick! Thanks
